language: cpp
sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
      group: travis_latest
      env: MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
      addons: { apt: { packages: ["clang-4.0"], sources: ["llvm-toolchain-trusty-4.0", "ubuntu-toolchain-r-test"] } }

    - os: linux
      dist: trusty
      group: travis_latest
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons: { apt: { packages: ["g++-7"], sources: ["ubuntu-toolchain-r-test"] } }

install:
  - eval "${MATRIX_EVAL}"
  - ${CXX} --version

  - which cmake
  - cmake --version

  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      if [[ "${CXX%%+*}" == "clang" ]]; then
        if [[ "${CXX}" == "clang++-4.0" ]]; then LLVM_VERSION="4.0.0";
        fi
        LLVM_URL="http://llvm.org/releases/${LLVM_VERSION}/llvm-${LLVM_VERSION}.src.tar.xz"
        LIBCXX_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxx-${LLVM_VERSION}.src.tar.xz"
        LIBCXXABI_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxxabi-${LLVM_VERSION}.src.tar.xz"
        mkdir -p llvm llvm/build llvm/projects/libcxx llvm/projects/libcxxabi
        travis_retry wget -O - ${LLVM_URL} | tar --strip-components=1 -xJ -C llvm
        travis_retry wget -O - ${LIBCXX_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxx
        travis_retry wget -O - ${LIBCXXABI_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxxabi
        (cd llvm/build && cmake .. -DCMAKE_INSTALL_PREFIX=${DEPS_DIR}/llvm/install)
        (cd llvm/build/projects/libcxx && make install -j2)
        (cd llvm/build/projects/libcxxabi && make install -j2)
        export CXXFLAGS="-isystem ${DEPS_DIR}/llvm/install/include/c++/v1"
        export LDFLAGS="-L ${DEPS_DIR}/llvm/install/lib -l c++ -l c++abi"
        export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${DEPS_DIR}/llvm/install/lib"
      fi
    fi

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DGENERATE_COVERAGE_INFO=ON ..
  - cmake --build .

script:
  - cd ${TRAVIS_BUILD_DIR}
  - cd build
  - ctest -C Debug

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - |
    for i in `seq 1 18`;
    do
      if (( $i < 10 )); then
          echo Result for day 0$i:
          cd 0$i
          ./advent0$i input
      else
        echo Result for day $i:
        cd $i
        ./advent$i input
      fi
      cd ..
    done
  - |
    if [[ "${CXX}" == "g++-7" ]]; then
        cmake --build . --target coverage
        bash <(curl -s https://codecov.io/bash)
    fi
